#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const WEB_DIR = path.join(ROOT, 'www');
const COPY_FILES = ['index.html', 'styles.css', 'app.js'];
const COPY_DIRS = ['assets'];

function assertPathExists(absPath) {
  if (!fs.existsSync(absPath)) {
    throw new Error(`Required path not found: ${absPath}`);
  }
}

function copyFile(relPath) {
  const src = path.join(ROOT, relPath);
  const dst = path.join(WEB_DIR, relPath);
  assertPathExists(src);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

function copyDir(relPath) {
  const src = path.join(ROOT, relPath);
  const dst = path.join(WEB_DIR, relPath);
  assertPathExists(src);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.cpSync(src, dst, { recursive: true, force: true });
}

function main() {
  fs.rmSync(WEB_DIR, { recursive: true, force: true });
  fs.mkdirSync(WEB_DIR, { recursive: true });

  COPY_FILES.forEach(copyFile);
  COPY_DIRS.forEach(copyDir);

  const stamp = path.join(WEB_DIR, '.cap-build.txt');
  fs.writeFileSync(
    stamp,
    `Generated by tools/prepare_capacitor_webdir.js\nBuilt: ${new Date().toISOString()}\n`,
    'utf8'
  );

  console.log('Prepared Capacitor webDir at:', WEB_DIR);
  console.log('Copied files:', COPY_FILES.join(', '));
  console.log('Copied directories:', COPY_DIRS.join(', '));
}

try {
  main();
} catch (err) {
  console.error('[cap:prepare] failed:', err.message);
  process.exit(1);
}
